In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_challenge.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hours),Snow inches (last 3 hours)
0,0,Ribeira Grande,PT,2020-02-23 06:34:04,38.52,-28.70,53.46,82,4,9.78,clear sky,0.0,0.0
1,1,Sur,OM,2020-02-23 06:43:29,22.57,59.53,75.81,51,1,4.47,clear sky,0.0,0.0
2,2,Ushuaia,AR,2020-02-23 06:36:08,-54.80,-68.30,48.20,70,40,34.45,scattered clouds,0.0,0.0
3,3,Waw,SS,2020-02-23 06:46:52,7.70,28.00,78.22,13,36,8.81,scattered clouds,0.0,0.0
4,4,Pisco,PE,2020-02-23 06:37:47,-13.70,-76.22,73.40,88,75,6.93,broken clouds,0.0,0.0

In [4]:
cols = city_data_df.columns.tolist()
cols

['City_ID',
 'City',
 'Country',
 'Date',
 'Lat',
 'Lng',
 'Max Temp',
 'Humidity',
 'Cloudiness',
 'Wind Speed',
 'Current Description',
 'Rain inches (last 3 hours)',
 'Snow inches (last 3 hours)']

In [5]:
# Prompt the customer for the minimum temperature preference.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
# Prompt the customer for the maximum temperature preference. 
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
# Prompt the customer to answer if he or she would like it to be raining or not.
rain = str(input('Do you want it to be raining? (yes/no)\n'))
# Prompt the customer to answer if he or she would like it to be snowing or not
snow = str(input('Do you want it to be snowing? (yes/no)\n'))

What is the minimum temperature you would like for your trip? 45
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no)
yes
Do you want it to be snowing? (yes/no)
no

In [6]:
# Filter the dataset to find the cities that fit the criteria.
for index, row in city_data_df.iterrows():
    if rain == "no":
        rain_inches = city_data_df["Rain inches (last 3 hours)"] == 0
    else:
        rain_inches = city_data_df["Rain inches (last 3 hours)"] != 0
    if snow == "no":
        snow_inches = city_data_df["Snow inches (last 3 hours)"] == 0
    else:
        snow_inches = city_data_df["Snow inches (last 3 hours)"] != 0

In [7]:

# Filter the dataset to find the cities that fit the criteria.

preferred_cities_df = city_data_df.loc[(city_data_df["Rain inches (last 3 hours)"] != rain_inches) &
                                       (city_data_df["Snow inches (last 3 hours)"] != snow_inches) &
                                       (city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
                                       
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hours),Snow inches (last 3 hours)
9,9,Richards Bay,ZA,2020-02-23 06:41:25,-28.78,32.04,77.25,79,100,39.12,light rain,2.56,0.0
21,21,East London,ZA,2020-02-23 06:37:40,-33.02,27.91,64.40,68,96,11.41,light rain,0.19,0.0
23,23,Puerto Ayora,EC,2020-02-23 06:37:09,-0.74,-90.35,78.01,100,68,4.63,light rain,0.56,0.0
24,24,Kirakira,SB,2020-02-23 06:46:56,-10.45,161.92,81.25,84,23,7.61,light rain,2.38,0.0
25,25,Saint-Philippe,RE,2020-02-23 06:33:36,-21.36,55.77,82.40,65,100,1.12,light rain,0.50,0.0
35,35,Port Alfred,ZA,2020-02-23 06:37:00,-33.59,26.89,69.01,72,55,3.00,light rain,0.13,0.0
54,54,Sao Francisco,BR,2020-02-23 06:47:02,-15.95,-44.86,70.50,97,100,3.58,light rain,2.44,0.0
61,61,Avarua,CK,2020-02-23 06:34:05,-21.21,-159.78,82.40,88,99,2.24,moderate rain,4.31,0.0
64,64,Kokstad,ZA,2020-02-23 06:47:05,-30.55,29.42,53.44,96,97,4.05,light rain,0.25,0.0
68,68,Gizo,SB,2020-02-23 06:37:35,-8.10,156.84,82.60,74,31,7.34,light rain,1.38,0.0

In [8]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
9,Richards Bay,ZA,77.25,light rain,-28.78,32.04,
21,East London,ZA,64.40,light rain,-33.02,27.91,
23,Puerto Ayora,EC,78.01,light rain,-0.74,-90.35,
24,Kirakira,SB,81.25,light rain,-10.45,161.92,
25,Saint-Philippe,RE,82.40,light rain,-21.36,55.77,
35,Port Alfred,ZA,69.01,light rain,-33.59,26.89,
54,Sao Francisco,BR,70.50,light rain,-15.95,-44.86,
61,Avarua,CK,82.40,moderate rain,-21.21,-159.78,
64,Kokstad,ZA,53.44,light rain,-30.55,29.42,
68,Gizo,SB,82.60,light rain,-8.10,156.84,

In [9]:
# Dependencies and Setup
import requests
import gmaps

# Import API key
from config import g_key

In [10]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [12]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")